"""
PROBE-suite dataclasses.

Mirrors AEGIS conventions where applicable (e.g. payload library dataclasses
in the existing five suites). The session is the unit of analysis for PROBE,
in contrast to the (payload_id, mas_id, phase) triplet used by static suites.

See RFC § 4.1 and § 5.2.
"""

# pylint: disable=fixme  # TODOs are intentional scaffold markers; will be removed as features land

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


class ProbeOutcomeReason(str, Enum):
    """Why a session terminated. Reported in the CSV `terminated_reason` column."""

    SUCCESS = "success"
    BUDGET_EXCEEDED = "budget_exceeded"
    ATTACKER_SELF_ABANDONED = "attacker_self_abandoned"
    VICTIM_CRASHED = "victim_crashed"
    ATTACKER_CRASHED = "attacker_crashed"
    JUDGE_UNAVAILABLE = "judge_unavailable"


class TurnVerdict(str, Enum):
    """Per-turn judge verdict from success_evaluator."""

    NO_PROGRESS = "no_progress"
    PARTIAL_PROGRESS = "partial_progress"
    SUCCESS = "success"


@dataclass(frozen=True)
class ProbeObjective:
    """
    Natural-language statement of what the attacker is trying to make the victim do.

    PROBE intentionally stores objectives, not payloads — payloads are generated by
    the attacker MAS at runtime, conditioned on objective + observation history.

    Fields mirror the static-suite payload dataclasses (`payload_id`, `severity`)
    plus PROBE-specific additions for cross-suite analysis.

    Attributes:
        objective_id:
            Globally unique within the objective library. Convention: `pr_<harm>_<n>`.
        harm_class:
            HarmBench-aligned category. TODO: align taxonomy with HarmBench v1.
        severity:
            One of "low", "medium", "high". Mirrors static-suite severity.
        objective_text:
            What the attacker is trying to achieve, in natural language.
        success_criterion:
            Concrete textual description of what counts as success — fed to the
            Tier 3 judge prompt.
        target_agent_role:
            Optional. If set, restricts the planner to attacking the named role.
            None ⇒ attacker free to choose.
        notes:
            Free-text. Not used at runtime.
    """

    objective_id: str
    harm_class: str
    severity: str
    objective_text: str
    success_criterion: str
    target_agent_role: Optional[str] = None
    notes: str = ""

    def __post_init__(self) -> None:
        # TODO: validate severity ∈ {"low","medium","high"} and harm_class ∈ taxonomy
        pass


@dataclass
class AttackIntent:
    """
    Output of the planner node, input to the payload_crafter node.

    Distinguishes the *strategy decision* (what angle to try) from the
    *concrete realization* (the actual prompt text). This separation is what
    lets us swap policies without changing the payload-crafting logic.
    """

    target_agent_role: str
    attack_angle: (
        str  # e.g. "appeal-to-authority", "satirical-framing", "context-flooding"
    )
    rationale: str  # planner's stated reason for choosing this angle
    rung_index: Optional[int] = None  # for Crescendo-style policies; None otherwise


@dataclass
class ProbeTurn:  # pylint: disable=too-many-instance-attributes
    """One turn in a multi-turn session."""

    turn_index: int
    intent: AttackIntent
    payload_text: str
    victim_output: dict[str, Any]  # full victim MAS state snapshot
    propagation_path: list[str]  # from AEGIS PropagationTracker
    influenced_agents: list[str]
    observation_summary: str  # output of victim_observer node
    verdict: TurnVerdict
    tier3_score: int  # 0-3 per AEGIS convention
    tier3_reasoning: str
    tier3_confidence: str  # "low"/"medium"/"high"
    duration_ms: float
    tokens_attacker: int
    tokens_victim: int
    tokens_judge: int


@dataclass
class ProbeOutcome:  # pylint: disable=too-many-instance-attributes
    """Final session-level outcome."""

    reason: ProbeOutcomeReason
    final_tier3_score: int  # max across turns
    turns_to_compromise: Optional[int]  # turn_index where max score first reached
    total_duration_ms: float
    total_tokens_attacker: int
    total_tokens_victim: int
    total_tokens_judge: int
    estimated_cost_usd: float


@dataclass
class ProbeSession:  # pylint: disable=too-many-instance-attributes
    """A multi-turn dialogue between attacker MAS and victim MAS."""

    session_id: str
    objective: ProbeObjective
    victim_mas_id: str
    victim_mas_path: str
    policy_name: str
    rng_seed: int
    attacker_model_config: dict[str, Any]
    judge_model_config: dict[str, Any]
    turns: list[ProbeTurn] = field(default_factory=list)
    final_outcome: Optional[ProbeOutcome] = None

    def to_csv_row(self) -> dict[str, Any]:
        """
        Render as a CSV row matching the cross-suite AEGIS schema.

        Per RFC § 14: shared columns kept, PROBE-specific columns appended.
        Static suites leave the appended columns blank; PROBE leaves
        `payload_id` and `phase` blank.

        TODO: verify column order matches `_helpers.py` if a master column list
        gets added there during integration.
        """
        # TODO: implement
        raise NotImplementedError

    def to_sidecar_json(self) -> dict[str, Any]:
        """Full multi-turn trajectory for `results/{mas_id}/sessions/{session_id}.json`."""
        # TODO: implement
        raise NotImplementedError
